### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [duongdominhchau/shprompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

This plugin also needs a readme with install instructions.

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by duongdominhchau** [comment]
Thank you for your attention. This is a project for fun with Git internal, so I didn't aim at an MVP initially. I've just added the minimal code to make it usable,  it's work time now so please wait for a day, I will add the docs and screenshots ASAP.

**Comment by duongdominhchau** [comment]
Done.
